name: Build and Deploy

on: [push]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Set up SSH on Bastion
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          JUMP_HOST: ${{ secrets.BASTION_HOST }}
          SERVER_HOST_1: ${{ secrets.SERVER_1_HOST }}
          SERVER_HOST_2: ${{ secrets.SERVER_2_HOST }}
        run: |
          # Set up SSH key for bastion server
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions

          # Add both HTTP servers to known hosts
          ssh-keyscan $SERVER_1_HOST >> ~/.ssh/known_hosts
          ssh-keyscan $SERVER_2_HOST >> ~/.ssh/known_hosts

          # Deploy to Server 1 via Bastion
          ssh -i ~/.ssh/github_actions $SSH_USERNAME@$BASTION_HOST "
            ssh $SSH_USERNAME@$SERVER_1_HOST '
              cd /docker-compose-flask-app &&
              git pull &&
              docker compose up -d --build
            '
          "

          # Deploy to Server 2 via Bastion
          ssh -i ~/.ssh/github_actions $SSH_USERNAME@$BASTION_HOST "
            ssh $SSH_USERNAME@$SERVER_2_HOST '
              cd /docker-compose-flask-app &&
              git pull &&
              docker compose up -d --build
            '
          "

      - name: Clean up SSH Key
        run: rm -f ~/.ssh/github_actions
