name: Deploy To Http Servers

on: [push]

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        servers: ["10.0.2.137", "10.0.2.138"]

    steps:
      - name: Add servers to known_hosts
        run: |
          ssh-keyscan -H 10.0.2.137 >> ~/.ssh/known_hosts
          ssh-keyscan -H 10.0.2.138 >> ~/.ssh/known_hosts

      - name: Deploy ${{ matrix.servers }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/ssh_key
          chmod 600 ~/.ssh/ssh_key
          
          ssh -T -i ~/.ssh/ssh_key $SSH_USERNAME@${{ matrix.servers }} "
            cd /Capstone-1 &&
            docker compose pull web &&
            docker compose up web -d &&
            docker image rm \$(docker image ls --filter dangling=true -q)
          "

          